### PR TITLE
Switch away from pdfjs dependency to cdn

### PR DESCRIPTION
**Pull request by ChrisKraljevicD2L**
`optionalChaining` begone

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
Should we maybe be hosting this on s.brightspace so that we don't have to rely on this cdn staying up/not doing malicious things

**Comment by ChrisKraljevicD2L** [comment]
Yep. Dunno how to do that though. I'll ask around.

**Comment by awikkerink** [comment]
Why not use https://github.com/Brightspace/d2l-pdf-viewer?

**Comment by ChrisKraljevicD2L** [comment]
> 
> 
> Why not use [Brightspace/d2l-pdf-viewer](https://github.com/Brightspace/d2l-pdf-viewer)?

That's a good idea. Right now this PR is just to get this repo building again. I can make followup PRs either making this component just `d2l-pdf-viewer` under the hood or removing this entirely and replacing any existing usages with `d2l-pdf-viewer`

**Comment by marcsoiferman** [comment]
Echoing Chris, this is needed to get it to build for fr-ON updates, not really looking to optimize any usage at this point

**Review by marcsoiferman — APPROVED** [review]
LGTM

**Review by jstefaniuk-d2l — APPROVED** [review]

**Pull request merged**
